### Get all categories
GET localhost:8080/api/categories/

### Get category by id
GET http://localhost:8080/api/categories/1

### Get an invalid category by id
GET http://localhost:8080/api/categories/99


### Create a new category
POST http://localhost:8080/api/categories/
Content-Type: application/json

{
  "id": 2,
  "name": "Mathematics",
  "slug": "maths",
  "dateCreated": "2026-02-26T22:10:00",
  "dateUpdated": null
}

### Updating category 2
PUT http://localhost:8080/api/categories/2
Content-Type: application/json

{
  "id": 2,
  "name": "Mathematics --- UPDATED !!!!",
  "slug": "mathsUPDATED",
  "dateCreated": "2026-02-26T22:10:00",
  "dateUpdated": null

}

### Updating unexisting category
PUT http://localhost:8080/api/categories/99
Content-Type: application/json

{
  "id": 99,
  "name": "Mathematics",
  "slug": "maths",
  "dateCreated": "2026-02-26T22:10:00",
  "dateUpdated": null

}

### Delete category 2
DELETE localhost:8080/api/categories/2

### Delete unexisting category
DELETE http://localhost:8080/api/categories/99