### Get all images
GET localhost:8080/api/images/

### Get image by id
GET http://localhost:8080/api/images/1

### Get an invalid image by id
GET http://localhost:8080/api/images/99


### Create a new image
POST http://localhost:8080/api/images/
Content-Type: application/json

{
  "id": 3,
  "altText": "Third Image Alt Text",
  "dateCreated": "2026-02-27T00:45:00",
  "dateUpdated": null,
  "isFeatured": true
}

### Updating image 3
PUT http://localhost:8080/api/images/3
Content-Type: application/json

{
  "id": 3,
  "altText": "Third Image Alt Text --- UPDATED !!!!",
  "dateCreated": "2026-02-27T00:45:00",
  "dateUpdated": "2026-02-27T01:00:00",
  "isFeatured": false
}

### Updating unexisting image
PUT http://localhost:8080/api/images/99
Content-Type: application/json

{
  "id": 99,
  "altText": "Non-existent Image",
  "dateCreated": "2026-02-27T00:45:00",
  "dateUpdated": null,
  "isFeatured": false
}

### Delete image 3
DELETE localhost:8080/api/images/3

### Delete unexisting image
DELETE http://localhost:8080/api/images/99
